### ISSUE TITLE
Exception: unexpected bad header during binary

### ISSUE THREAD

**Issue by jefferyto** [garlicoin-project/garlium#6]
I upgraded to Ubuntu 22.04 (from 21.10) and Garlium stopped updating blockchain data from the network. The error I get at the console (outputted repeatedly):

```
E/i | ..interface.[ca.node.garlico.in:50002] | Exception in run: Exception("unexpected bad header during binary: {'version': 536870912, 'prev_block_hash': '4e55cf5183cb72b3843b5bfa68f97bedd06c397d6e96fb59bf31ae515df44bdc', 'merkle_root': 'd80d6a426cd712031721ace611cb20b788675b0f69d977f6c9558a86b29cb52a', 'timestamp': 1651391681, 'bits': 470624532, 'nonce': 2638877444, 'block_height': 3282723}")
Traceback (most recent call last):
  File "/home/jeff/Code/tools/garlium/electrum_grlc/util.py", line 1106, in wrapper
    return await func(*args, **kwargs)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 487, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 510, in run
    await self.open_session(ssl_context)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 653, in open_session
    async with self.taskgroup as group:
  File "/home/jeff/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/home/jeff/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 717, in run_fetch_blocks
    await self._process_header_at_tip()
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 731, in _process_header_at_tip
    _, height = await self.step(height, header)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 787, in step
    good, bad, bad_header = await self._search_headers_binary(height, bad, bad_header, chain)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 814, in _search_headers_binary
    raise Exception('unexpected bad header during binary: {}'.format(bad_header))
Exception: unexpected bad header during binary: {'version': 536870912, 'prev_block_hash': '4e55cf5183cb72b3843b5bfa68f97bedd06c397d6e96fb59bf31ae515df44bdc', 'merkle_root': 'd80d6a426cd712031721ace611cb20b788675b0f69d977f6c9558a86b29cb52a', 'timestamp': 1651391681, 'bits': 470624532, 'nonce': 2638877444, 'block_height': 3282723}
```

If I delete blockchain_headers (in ~/.config/garlium), it downloads data from the beginning and eventually stops at block height 58670:

```
E/i | ..interface.[uk.garlium.crapules.org:50002] | Exception in run: Exception("unexpected bad header during binary: {'version': 536870912, 'prev_block_hash': '4c2cd9113c6a512dfb76aafa3d1d24329326678fbfef8b48beecb982d81da088', 'merkle_root': '07c32fcab88033d7e00a0c9236ca1be057fbf7c1b9d86f151953c9b429618a84', 'timestamp': 1518816555, 'bits': 469990327, 'nonce': 3979683713, 'block_height': 58671}")
Traceback (most recent call last):
  File "/home/jeff/Code/tools/garlium/electrum_grlc/util.py", line 1106, in wrapper
    return await func(*args, **kwargs)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 487, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 510, in run
    await self.open_session(ssl_context)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 653, in open_session
    async with self.taskgroup as group:
  File "/home/jeff/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/home/jeff/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 717, in run_fetch_blocks
    await self._process_header_at_tip()
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 731, in _process_header_at_tip
    _, height = await self.step(height, header)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 787, in step
    good, bad, bad_header = await self._search_headers_binary(height, bad, bad_header, chain)
  File "/home/jeff/Code/tools/garlium/electrum_grlc/interface.py", line 814, in _search_headers_binary
    raise Exception('unexpected bad header during binary: {}'.format(bad_header))
Exception: unexpected bad header during binary: {'version': 536870912, 'prev_block_hash': '4c2cd9113c6a512dfb76aafa3d1d24329326678fbfef8b48beecb982d81da088', 'merkle_root': '07c32fcab88033d7e00a0c9236ca1be057fbf7c1b9d86f151953c9b429618a84', 'timestamp': 1518816555, 'bits': 469990327, 'nonce': 3979683713, 'block_height': 58671}
```

**Comment by HoorayJorge** [comment]
I believe that's the hard fork block, without looking, but the timing looks right.  I will look into this but we might need the dev.  Is this an amd64 or arm64 machine?  I've had a few issues with some of the crypto libraries on the newer versions of ubuntu, but mostly on ARM.

**Comment by jefferyto** [comment]
amd64 - it was working on 21.10.
