### ISSUE TITLE
20 hours sync, and still at 2019 year

### ISSUE THREAD

**Issue by Starec666** [garlicoin-project/garlium#7]
Hi! I've updated 2.0 to 4.0, created new wallet from the seed. And sync had started. it was yesterday. Now it is still syncing, history shows me the beginning of 2019 year. I think somethnig is going wrong with "light" wallet?
New coins appears but very slowly.

**Comment by Starec666** [comment]
20220718T192257.936837Z |    ERROR | ..interface.[au.garlium.crapules.org:50002] | Exception in run: AttributeError("'NoneType' object has no attribute 'get'")
Traceback (most recent call last):
  File "electrum_grlc\util.py", line 1106, in wrapper
  File "electrum_grlc\interface.py", line 487, in wrapper_func
  File "electrum_grlc\interface.py", line 510, in run
  File "electrum_grlc\interface.py", line 657, in open_session
  File "aiorpcx\curio.py", line 255, in __aexit__
  File "aiorpcx\curio.py", line 213, in join
  File "electrum_grlc\interface.py", line 721, in run_fetch_blocks
  File "electrum_grlc\network.py", line 672, in switch_unwanted_fork_interface
  File "electrum_grlc\blockchain.py", line 730, in get_chains_that_contain_header
  File "electrum_grlc\blockchain.py", line 730, in <lambda>
  File "electrum_grlc\util.py", line 1138, in func_wrapper
  File "electrum_grlc\blockchain.py", line 644, in get_chainwork
  File "electrum_grlc\blockchain.py", line 622, in chainwork_of_header_at_height
  File "electrum_grlc\blockchain.py", line 549, in get_target
AttributeError: 'NoneType' object has no attribute 'get'


this code repeats in log file many times

**Comment by alexw3f** [comment]
did you try to close garlium and delete the blockchain_headers.dat file and start it again? in the past that was sometimes a cause of malfunction
